// Auto-generated by: pnpm db:types
// Run `pnpm db:types` after schema changes to regenerate.
// Manual placeholder — replace with: supabase gen types typescript --local

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      households: {
        Row: { id: string; name: string; created_at: string };
        Insert: { id?: string; name: string; created_at?: string };
        Update: { id?: string; name?: string };
        Relationships: [];
      };
      profiles: {
        Row: { id: string; household_id: string; name: string; role: 'admin' | 'operator'; created_at: string };
        Insert: { id: string; household_id: string; name: string; role: 'admin' | 'operator' };
        Update: { name?: string; role?: 'admin' | 'operator' };
        Relationships: [];
      };
      entities: {
        Row: { id: string; household_id: string; name: string; type: 'personal' | 'business' | 'shared'; color: string; cnpj: string | null; active: boolean; created_at: string };
        Insert: { id?: string; household_id: string; name: string; type: 'personal' | 'business' | 'shared'; color?: string; cnpj?: string | null; active?: boolean };
        Update: { name?: string; color?: string; cnpj?: string | null; active?: boolean };
        Relationships: [];
      };
      accounts: {
        Row: { id: string; household_id: string; name: string; kind: 'credit_card' | 'checking' | 'company' | 'investment'; brand?: string | null; opening_balance: number; active: boolean; created_at: string; entity_id: string | null };
        Insert: { id?: string; household_id: string; name: string; kind: 'credit_card' | 'checking' | 'company' | 'investment'; brand?: string | null; opening_balance?: number; active?: boolean; entity_id?: string | null };
        Update: { name?: string; kind?: 'credit_card' | 'checking' | 'company' | 'investment'; brand?: string | null; active?: boolean; entity_id?: string | null };
        Relationships: [];
      };
      categories: {
        Row: { id: string; household_id: string; name: string; default_responsible: string | null };
        Insert: { id?: string; household_id: string; name: string; default_responsible?: string | null };
        Update: { name?: string; default_responsible?: string | null };
        Relationships: [];
      };
      csv_imports: {
        Row: { id: string; household_id: string; filename: string; account_id: string; imported_at: string; imported_by: string | null; rows_total: number; rows_inserted: number; rows_skipped_duplicate: number; rows_flagged_review: number; rows_auto_assigned: number; raw_content_sha256: string };
        Insert: { id?: string; household_id: string; filename: string; account_id: string; imported_by?: string | null; rows_total: number; rows_inserted: number; rows_skipped_duplicate: number; rows_flagged_review: number; rows_auto_assigned: number; raw_content_sha256: string };
        Update: Record<string, never>;
        Relationships: [];
      };
      transactions: {
        Row: { id: string; household_id: string; account_id: string; occurred_on: string; description: string; amount: number; responsible: string; category_id: string | null; status: string; source: string; csv_import_id: string | null; fingerprint: string; notes: string | null; created_at: string; updated_at: string; created_by: string | null; installment_current: number | null; installment_total: number | null; entity_id: string | null; is_transfer: boolean; transfer_id: string | null };
        Insert: { id?: string; household_id: string; account_id: string; occurred_on: string; description: string; amount: number; responsible?: string; category_id?: string | null; status?: string; source: string; csv_import_id?: string | null; fingerprint: string; notes?: string | null; created_by?: string | null; installment_current?: number | null; installment_total?: number | null; entity_id?: string | null; is_transfer?: boolean; transfer_id?: string | null };
        Update: { responsible?: string; category_id?: string | null; status?: string; notes?: string | null; installment_current?: number | null; installment_total?: number | null; entity_id?: string | null; is_transfer?: boolean; transfer_id?: string | null };
        Relationships: [];
      };
      recurring_commitments: {
        Row: { id: string; household_id: string; description: string; amount: number; responsible: string; paid_by: 'iremar' | 'juliana' | 'casal' | 'i2'; account_id: string | null; due_day: number; category_id: string | null; variable: boolean; active: boolean; notes: string | null; payment_method: 'credit_card' | 'boleto' | 'pix'; recurrence_type: 'monthly' | 'weekly' | 'bimonthly' | 'quarterly' | 'semiannual' | 'annual'; entity_id: string | null };
        Insert: { id?: string; household_id: string; description: string; amount: number; responsible: string; paid_by: 'iremar' | 'juliana' | 'casal' | 'i2'; account_id?: string | null; due_day: number; category_id?: string | null; variable?: boolean; active?: boolean; notes?: string | null; payment_method?: 'credit_card' | 'boleto' | 'pix'; recurrence_type?: 'monthly' | 'weekly' | 'bimonthly' | 'quarterly' | 'semiannual' | 'annual'; entity_id?: string | null };
        Update: { amount?: number; active?: boolean; notes?: string | null; payment_method?: 'credit_card' | 'boleto' | 'pix'; recurrence_type?: 'monthly' | 'weekly' | 'bimonthly' | 'quarterly' | 'semiannual' | 'annual'; entity_id?: string | null; description?: string; due_day?: number; responsible?: string; paid_by?: 'iremar' | 'juliana' | 'casal' | 'i2'; account_id?: string | null };
        Relationships: [];
      };
      monthly_obligations: {
        Row: { id: string; household_id: string; recurring_id: string | null; reference_month: string; due_date: string; description: string; amount: number; responsible: string; paid_by: 'iremar' | 'juliana' | 'casal' | 'i2' | null; status: string; paid_on: string | null; paid_amount: number | null };
        Insert: { id?: string; household_id: string; recurring_id?: string | null; reference_month: string; due_date: string; description: string; amount: number; responsible: string; paid_by?: 'iremar' | 'juliana' | 'casal' | 'i2' | null; status?: string; paid_on?: string | null; paid_amount?: number | null };
        Update: { status?: string; paid_on?: string | null; paid_amount?: number | null; amount?: number; paid_by?: 'iremar' | 'juliana' | 'casal' | 'i2' | null };
        Relationships: [];
      };
      transfers: {
        Row: { id: string; household_id: string; from_account_id: string; to_account_id: string; amount: number; occurred_on: string; description: string | null; from_transaction_id: string | null; to_transaction_id: string | null; created_by: string | null; created_at: string };
        Insert: { id?: string; household_id: string; from_account_id: string; to_account_id: string; amount: number; occurred_on: string; description?: string | null; from_transaction_id?: string | null; to_transaction_id?: string | null; created_by?: string | null };
        Update: { amount?: number; occurred_on?: string; description?: string | null; from_transaction_id?: string | null; to_transaction_id?: string | null };
        Relationships: [];
      };
      categorization_rules: {
        Row: { id: string; household_id: string; match_pattern: string; responsible: string; category_id: string | null; confidence: number; hits: number; created_from_manual: boolean };
        Insert: { id?: string; household_id: string; match_pattern: string; responsible: string; category_id?: string | null; confidence?: number; hits?: number; created_from_manual?: boolean };
        Update: { responsible?: string; confidence?: number; hits?: number };
        Relationships: [];
      };
      monthly_settlements: {
        Row: { id: string; household_id: string; reference_month: string; iremar_part: number; juliana_part: number; i2_part: number; casal_total: number; total_fatura: number; juliana_transferred: number | null; iremar_transferred: number | null; credit_carried_to_juliana: number; credit_carried_to_iremar: number; pro_labore: number; i2_reimbursements: number; other_income: number; fixed_commitments_total: number; closed_at: string | null; closed_by: string | null };
        Insert: { id?: string; household_id: string; reference_month: string; iremar_part: number; juliana_part: number; i2_part: number; casal_total: number; total_fatura: number; juliana_transferred?: number | null; pro_labore?: number; i2_reimbursements?: number; other_income?: number; fixed_commitments_total?: number };
        Update: { juliana_transferred?: number | null; iremar_transferred?: number | null; closed_at?: string | null };
        Relationships: [];
      };
      income_records: {
        Row: { id: string; household_id: string; occurred_on: string; description: string; amount: number; kind: string; reference_month: string | null; created_by: string | null; created_at: string; entity_id: string | null };
        Insert: { id?: string; household_id: string; occurred_on: string; description: string; amount: number; kind: string; reference_month?: string | null; created_by?: string | null; entity_id?: string | null };
        Update: { amount?: number; description?: string; entity_id?: string | null };
        Relationships: [];
      };
      fiscal_notes: {
        Row: {
          id: string;
          household_id: string;
          income_record_id: string;
          nf_number: string;
          nf_amount: number;
          nf_issued_at: string;
          competencia: string | null;
          tomador: string | null;
          aliquota_iss: number | null;
          iss_amount: number | null;
          net_amount: number | null;
          file_url: string | null;
          file_path: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          income_record_id: string;
          nf_number: string;
          nf_amount: number;
          nf_issued_at: string;
          competencia?: string | null;
          tomador?: string | null;
          aliquota_iss?: number | null;
          iss_amount?: number | null;
          net_amount?: number | null;
          file_url?: string | null;
          file_path?: string | null;
          notes?: string | null;
        };
        Update: {
          nf_number?: string;
          nf_amount?: number;
          nf_issued_at?: string;
          competencia?: string | null;
          tomador?: string | null;
          aliquota_iss?: number | null;
          iss_amount?: number | null;
          net_amount?: number | null;
          file_url?: string | null;
          file_path?: string | null;
          notes?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      transaction_attachments: {
        Row: { id: string; household_id: string; transaction_id: string; file_name: string; file_path: string; file_url: string | null; mime_type: string | null; size_bytes: number | null; kind: string | null; notes: string | null; uploaded_by: string | null; created_at: string };
        Insert: { id?: string; household_id: string; transaction_id: string; file_name: string; file_path: string; file_url?: string | null; mime_type?: string | null; size_bytes?: number | null; kind?: string | null; notes?: string | null; uploaded_by?: string | null };
        Update: { file_name?: string; kind?: string | null; notes?: string | null; file_url?: string | null };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      get_my_household_id: { Args: Record<string, never>; Returns: string };
      get_my_role: { Args: Record<string, never>; Returns: string };
      increment_rule_hits: { Args: { p_household_id: string; p_pattern: string }; Returns: void };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
